--- 
abstract: A Distributed Job Queue
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Swarmage
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::CLI: 0
  Class::Accessor::Grouped: 0
  Class::C3::Componentised: 0
  Class::Inspector: 0
  Class::Null: 0
  Config::Any: 0
  Digest::MD5: 0
  MIME::Base64: 0
  Net::Stomp: 0
  Storable: 0
  UNIVERSAL::isa: 0
  UNIVERSAL::require: 0
tests: t/*.t t/*/*.t
version: 0.00004
