--- 
abstract: A Distributed Job Queue
author: 
  - Copyright (c) 2007-2008 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Swarmage
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires: 
  BerkeleyDB: 0
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 0
  DBI: 0
  Digest::MD5: 0
  Event::Notify: 0
  IO::Handle: 0
  Log::Dispatch: 0
  Log::Dispatch::Handle: 0
  MIME::Base64: 0
  POE: 0
  POE::Component::Generic: 0
  POE::Component::IKC: 0
  Path::Class: 0
  Storable: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
tests: t/*.t t/*/*.t t/*/*/*.t
version: 0.01003
